config/routes.rb
Rails.application.routes.draw do
  resources :orders
  
  root "orders#index"

end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def new

  end
  
  def create
     @order = Order.new(order_params)
     @order.save
    redirect_to @order
  end

  def show
    @order = Order.find(params[:id])
  end

  private
    def order_params
      params.require(:order).permit(:title, :reward, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<html>
<head>
  <title>TesteeApp</title>
  <p>
  Happy New year!!
  </p>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/orders/index.html.erb
<h1>記事一覧</h1>
<%= link_to "New Order", new_order_path %>
<table>
  <tr>
   <th>Title</th>
   <th>u_id</th>
   <th colspan="1"></th>
  </tr>
<% @orders.each do |order| %>
  <tr>
    <td><%= order.title %></td>
    <td><%= order.user_id %></td>
    <td><%= link_to "Show", order_path(order) %></td>
  </tr>
<% end %>
</table>

app/views/orders/new.html.erb
<h1>New Article</h1>
<%= form_for :order, url: orders_path do |f| %>
  <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
  </p>

  <p>
      <%= f.label :award %><br>
      <%= f.text_field :award %>
  </p>    
  <p>
     <%= f.label :content %><br>
     <%= f.text_area :content %>
  </p>
  
  <p>
  <%= f.submit %>
  </p>
<% end %>
<%= link_to "Back", orders_path %>

app/views/orders/show.html.erb
<h1><%= @order.title %></h1>
<p><%= @order.content %></p>
<ul>
  <li>報酬 : <%= @order.award %></li>
  <li>投稿者 : <%= @order.owner_id %></li>
</ul>
<%= link_to "戻る", orders_path %>